import { InstrumentInfo, ReverbPreset } from '@/types/piano';

export const AVAILABLE_REVERBS: { id: ReverbPreset; name: string; description: string }[] = [
  { id: 'off', name: 'Dry / Off', description: 'Zero reverberation, direct intimate sound' },
  { id: 'studio', name: 'Dry Studio', description: 'Treated recording booth with tight acoustic absorption (0.8s)' },
  { id: 'room', name: 'Recording Room', description: 'Subtle warm room reflections and natural presence (1.4s)' },
  { id: 'hall', name: 'Concert Hall', description: 'Lush symphonic auditorium acoustics (2.8s decay)' },
  { id: 'cathedral', name: 'Cathedral', description: 'Expansive stone sanctuary reverb (5.0s decay)' },
];

export const TUNING_PRESETS = [
  { label: '432 Hz', value: 432, desc: 'Verdi / Natural resonance pitch' },
  { label: '440 Hz', value: 440, desc: 'Concert Pitch standard (ISO 16)' },
  { label: '442 Hz', value: 442, desc: 'European Symphony Orchestra standard' },
];

export const INSTRUMENT_CATEGORIES: { id: string; name: string }[] = [
  { id: 'Grand Pianos', name: 'Grand Pianos' },
  { id: 'Upright Pianos', name: 'Upright Pianos' },
  { id: 'Electric Pianos', name: 'Electric Pianos' },
  { id: 'Keys', name: 'Keys' },
  { id: 'Organ', name: 'Organ' },
  { id: 'Strings', name: 'Strings' },
  { id: 'Pads', name: 'Pads' },
  { id: 'Hybrid', name: 'Hybrid' },
];

export const TIME_SIGNATURES = [
  { label: '4/4', value: 4, desc: 'Common time (4 quarter beats)' },
  { label: '3/4', value: 3, desc: 'Waltz time (3 quarter beats)' },
  { label: '2/4', value: 2, desc: 'March time (2 quarter beats)' },
  { label: '6/8', value: 6, desc: 'Compound duple time (6 eighth beats)' },
];

export const AVAILABLE_INSTRUMENTS: InstrumentInfo[] = [
  // ================= CATEGORY 1 — GRAND PIANOS =================
  {
    id: 'concert-grand',
    name: 'Concert Grand',
    category: 'Grand Pianos',
    description: 'Full-bodied 9-foot concert grand with hammer felt transient, soundboard body resonance and rich harmonic overtones.',
    icon: 'Piano',
    brightness: 60,
    attack: 0.003,
    release: 0.35,
    reverb: 'hall',
  },
  {
    id: 'studio-grand',
    name: 'Studio Grand',
    category: 'Grand Pianos',
    description: 'Crisp, articulate German grand tailored for close recording and dynamic pop/jazz mix clarity.',
    icon: 'Music',
    brightness: 68,
    attack: 0.002,
    release: 0.28,
    reverb: 'studio',
  },
  {
    id: 'bright-grand',
    name: 'Bright Grand',
    category: 'Grand Pianos',
    description: 'Punchy Japanese concert grand with sharp hammer attack and vibrant, crystalline upper partials.',
    icon: 'Sparkles',
    brightness: 82,
    attack: 0.002,
    release: 0.25,
    reverb: 'hall',
  },
  {
    id: 'warm-grand',
    name: 'Warm Grand',
    category: 'Grand Pianos',
    description: 'Rich, rounded European grand with attenuated top-end and woody, enveloping lower registers.',
    icon: 'Volume1',
    brightness: 45,
    attack: 0.004,
    release: 0.38,
    reverb: 'room',
  },
  {
    id: 'soft-grand',
    name: 'Soft Grand',
    category: 'Grand Pianos',
    description: 'Intimate, gentle touch grand for delicate lyrical passages and impressionistic textures.',
    icon: 'Feather',
    brightness: 38,
    attack: 0.006,
    release: 0.42,
    reverb: 'hall',
  },
  {
    id: 'cinematic-grand',
    name: 'Cinematic Grand',
    category: 'Grand Pianos',
    description: 'Spacious scoring stage grand with deep sub-octaves, extended decay, and dramatic presence.',
    icon: 'Film',
    brightness: 55,
    attack: 0.005,
    release: 0.65,
    reverb: 'cathedral',
  },
  {
    id: 'classical-grand',
    name: 'Classical Grand',
    category: 'Grand Pianos',
    description: 'Balanced Vienna grand with pure even harmonics and transparent polyphonic counterpoint.',
    icon: 'Disc',
    brightness: 52,
    attack: 0.003,
    release: 0.32,
    reverb: 'hall',
  },
  {
    id: 'vintage-grand',
    name: 'Vintage Grand',
    category: 'Grand Pianos',
    description: 'Aged 1920s parlor grand with subtle pitch character, gentle warmth, and nostalgic patina.',
    icon: 'Radio',
    brightness: 44,
    attack: 0.004,
    release: 0.36,
    reverb: 'room',
  },

  // ================= CATEGORY 2 — UPRIGHT PIANOS =================
  {
    id: 'classic-upright',
    name: 'Classic Upright',
    category: 'Upright Pianos',
    description: 'Warm, intimate acoustic parlor upright with close-mic presence and subtle wooden cabinet resonance.',
    icon: 'Music2',
    brightness: 54,
    attack: 0.003,
    release: 0.22,
    reverb: 'room',
  },
  {
    id: 'warm-upright',
    name: 'Warm Upright',
    category: 'Upright Pianos',
    description: 'Cozy living-room upright with rounded hammers and gentle wooden body bloom.',
    icon: 'Home',
    brightness: 46,
    attack: 0.004,
    release: 0.26,
    reverb: 'room',
  },
  {
    id: 'vintage-upright',
    name: 'Vintage Upright',
    category: 'Upright Pianos',
    description: 'Characterful honky-tonk / ragtime upright with distinct acoustic personality and bite.',
    icon: 'Clock',
    brightness: 72,
    attack: 0.002,
    release: 0.19,
    reverb: 'room',
  },
  {
    id: 'felt-upright',
    name: 'Felt Upright',
    category: 'Upright Pianos',
    description: 'Acoustic upright with a thick damping felt strip between hammers and strings for a whisper-quiet tone.',
    icon: 'Feather',
    brightness: 32,
    attack: 0.008,
    release: 0.45,
    reverb: 'hall',
  },
  {
    id: 'dark-upright',
    name: 'Dark Upright',
    category: 'Upright Pianos',
    description: 'Moody, muted acoustic piano ideal for nocturnal jazz and melancholic neo-classical ballads.',
    icon: 'Moon',
    brightness: 30,
    attack: 0.006,
    release: 0.35,
    reverb: 'hall',
  },

  // ================= CATEGORY 3 — ELECTRIC PIANOS =================
  {
    id: 'electric-piano',
    name: 'Classic Electric Piano',
    category: 'Electric Pianos',
    description: 'Classic 1970s tine-based electric piano with warm bell transient and mellow harmonic sustain.',
    icon: 'Zap',
    brightness: 58,
    attack: 0.002,
    release: 0.24,
    reverb: 'room',
  },
  {
    id: 'rhodes',
    name: 'Rhodes Mark I',
    category: 'Electric Pianos',
    description: 'Legendary electro-mechanical tine piano with deep fundamental bell sound and sweet overdrive tone.',
    icon: 'Sparkles',
    brightness: 62,
    attack: 0.002,
    release: 0.26,
    reverb: 'room',
  },
  {
    id: 'wurlitzer',
    name: 'Wurlitzer 200A',
    category: 'Electric Pianos',
    description: 'Gritty 1960s reed-based electric piano with distinct mid-range bite and dynamic vintage bark.',
    icon: 'Zap',
    brightness: 66,
    attack: 0.002,
    release: 0.20,
    reverb: 'studio',
  },
  {
    id: 'fm-electric-piano',
    name: 'FM Electric Piano',
    category: 'Electric Pianos',
    description: 'Iconic 1980s 6-operator frequency modulation digital piano with glass-like bell chime.',
    icon: 'Radio',
    brightness: 78,
    attack: 0.001,
    release: 0.32,
    reverb: 'hall',
  },
  {
    id: 'suitcase-ep',
    name: 'Suitcase Electric Piano',
    category: 'Electric Pianos',
    description: 'Stereo vibrato-amped electric piano with wide spatial movement and lush velvet sustain.',
    icon: 'Sliders',
    brightness: 60,
    attack: 0.002,
    release: 0.28,
    reverb: 'room',
  },

  // ================= CATEGORY 4 — KEYS =================
  {
    id: 'clavinet',
    name: 'Clavinet D6',
    category: 'Keys',
    description: 'Funky percussive struck-reed key instrument with sharp pluck transient and twangy bite.',
    icon: 'Activity',
    brightness: 84,
    attack: 0.001,
    release: 0.12,
    reverb: 'studio',
  },
  {
    id: 'soft-keys',
    name: 'Soft Keys',
    category: 'Keys',
    description: 'Mellow low-pass filtered electronic key sound with tape warmth and gentle pitch flutter.',
    icon: 'Feather',
    brightness: 42,
    attack: 0.005,
    release: 0.28,
    reverb: 'hall',
  },
  {
    id: 'vintage-keys',
    name: 'Vintage Keys',
    category: 'Keys',
    description: 'Analog combo organ-piano hybrid with transistor warmth and retro psychedelic flair.',
    icon: 'Disc',
    brightness: 64,
    attack: 0.003,
    release: 0.22,
    reverb: 'room',
  },

  // ================= CATEGORY 5 — ORGAN =================
  {
    id: 'jazz-organ',
    name: 'Jazz Organ (B3)',
    category: 'Organ',
    description: 'Soulful tonewheel drawbar organ with fast percussive key-click and rich harmonic overtone mix.',
    icon: 'Sliders',
    brightness: 68,
    attack: 0.004,
    release: 0.08,
    reverb: 'room',
  },
  {
    id: 'church-organ',
    name: 'Church Organ',
    category: 'Organ',
    description: 'Grand liturgical pipe organ with stacked 16\', 8\', 4\' pipe ranks and sustaining majesty.',
    icon: 'Church',
    brightness: 60,
    attack: 0.015,
    release: 0.12,
    reverb: 'cathedral',
  },
  {
    id: 'rock-organ',
    name: 'Rock Organ',
    category: 'Organ',
    description: 'Aggressive saturated drawbar organ driven hard with harmonic grit and full upper stops.',
    icon: 'Zap',
    brightness: 76,
    attack: 0.003,
    release: 0.06,
    reverb: 'room',
  },
  {
    id: 'soft-organ',
    name: 'Soft Flute Organ',
    category: 'Organ',
    description: 'Mellow wooden flute pipe organ with pure sine foundation and gentle spiritual tone.',
    icon: 'Feather',
    brightness: 40,
    attack: 0.020,
    release: 0.15,
    reverb: 'cathedral',
  },

  // ================= CATEGORY 6 — STRINGS =================
  {
    id: 'solo-strings',
    name: 'Solo Cello & Violin',
    category: 'Strings',
    description: 'Expressive acoustic solo bowed strings with delicate vibrato and natural bow noise.',
    icon: 'Music',
    brightness: 56,
    attack: 0.08,
    release: 0.35,
    reverb: 'hall',
  },
  {
    id: 'string-ensemble',
    name: 'String Ensemble',
    category: 'Strings',
    description: 'Lush 40-piece symphonic string orchestra with full violin, viola, cello, and double-bass spread.',
    icon: 'Disc',
    brightness: 62,
    attack: 0.12,
    release: 0.45,
    reverb: 'hall',
  },
  {
    id: 'warm-strings',
    name: 'Warm Strings',
    category: 'Strings',
    description: 'Muted chamber string ensemble with velvet bow texture and dark, emotive harmonic bloom.',
    icon: 'Volume1',
    brightness: 44,
    attack: 0.10,
    release: 0.40,
    reverb: 'cathedral',
  },
  {
    id: 'cinematic-strings',
    name: 'Cinematic Strings',
    category: 'Strings',
    description: 'Epic Hollywood scoring stage string orchestra with soaring high registers and resonant basses.',
    icon: 'Film',
    brightness: 70,
    attack: 0.07,
    release: 0.55,
    reverb: 'cathedral',
  },

  // ================= CATEGORY 7 — PADS =================
  {
    id: 'warm-pad',
    name: 'Warm Pad',
    category: 'Pads',
    description: 'Deep analog polyphonic synth pad with gently modulated cut-off and enveloping body.',
    icon: 'Sun',
    brightness: 42,
    attack: 0.18,
    release: 0.60,
    reverb: 'cathedral',
  },
  {
    id: 'ambient-pad',
    name: 'Ambient Pad',
    category: 'Pads',
    description: 'Ethereal, shimmering dream pad with slow sweeping harmonics and expansive stereo diffusion.',
    icon: 'Wind',
    brightness: 58,
    attack: 0.25,
    release: 0.85,
    reverb: 'cathedral',
  },
  {
    id: 'cinematic-pad',
    name: 'Cinematic Pad',
    category: 'Pads',
    description: 'Dramatically filtered motion pad with deep sub-bass bed and subtle celestial highlights.',
    icon: 'Film',
    brightness: 50,
    attack: 0.20,
    release: 0.70,
    reverb: 'cathedral',
  },
  {
    id: 'synth-pad',
    name: 'Synth Pad',
    category: 'Pads',
    description: 'Classic dual-oscillator sawtooth synth pad with warm chorus and rich analog presence.',
    icon: 'Activity',
    brightness: 64,
    attack: 0.15,
    release: 0.50,
    reverb: 'hall',
  },

  // ================= CATEGORY 8 — HYBRID =================
  {
    id: 'piano-strings',
    name: 'Piano + Strings',
    category: 'Hybrid',
    description: 'Concert Grand layer combined with a symphonic string orchestra bed for emotive ballad accompaniment.',
    icon: 'Layers',
    brightness: 62,
    attack: 0.003,
    release: 0.48,
    reverb: 'hall',
  },
  {
    id: 'piano-pad',
    name: 'Piano + Ambient Pad',
    category: 'Hybrid',
    description: 'Crisp acoustic grand piano backed by an ethereal ambient pad that sustains beneath chords.',
    icon: 'Cloud',
    brightness: 60,
    attack: 0.003,
    release: 0.65,
    reverb: 'cathedral',
  },
  {
    id: 'piano-choir',
    name: 'Piano + Choir',
    category: 'Hybrid',
    description: 'Majestic grand piano combined with a serene human vocal choir pad for sacred and choral works.',
    icon: 'Users',
    brightness: 54,
    attack: 0.003,
    release: 0.55,
    reverb: 'cathedral',
  },
  {
    id: 'piano-synth',
    name: 'Piano + Synth',
    category: 'Hybrid',
    description: 'Punchy studio piano layered with a warm analog synthesizer brass/lead for modern crossover tracks.',
    icon: 'Cpu',
    brightness: 70,
    attack: 0.002,
    release: 0.40,
    reverb: 'hall',
  },
];

// Helper to resolve legacy aliases
export function resolveInstrument(id: string): InstrumentInfo {
  const map: Record<string, string> = {
    'acoustic-grand': 'concert-grand',
    'bright-piano': 'bright-grand',
    'upright-piano': 'classic-upright',
    'soft-piano': 'soft-grand',
    'pipe-organ': 'church-organ',
    'strings-pad': 'string-ensemble',
    'analog-synth': 'synth-pad',
  };
  const targetId = map[id] || id;
  const found = AVAILABLE_INSTRUMENTS.find((i) => i.id === targetId);
  return found || AVAILABLE_INSTRUMENTS[0];
}

export interface ScaleDefinition {
  id: string;
  name: string;
  root: string;
  type: string;
  description: string;
  notes: string[];
}

export const SCALES_LIST: ScaleDefinition[] = [
  {
    id: 'none',
    name: 'No Scale (Chromatic)',
    root: 'C',
    type: 'chromatic',
    description: 'All 12 chromatic pitches available without filtering',
    notes: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
  },
  {
    id: 'c-major',
    name: 'C Major (Natural)',
    root: 'C',
    type: 'major',
    description: 'The foundation scale with all white keys: C, D, E, F, G, A, B',
    notes: ['C', 'D', 'E', 'F', 'G', 'A', 'B'],
  },
  {
    id: 'g-major',
    name: 'G Major (1 Sharp: F#)',
    root: 'G',
    type: 'major',
    description: 'Bright and resonant standard key: G, A, B, C, D, E, F#',
    notes: ['G', 'A', 'B', 'C', 'D', 'E', 'F#'],
  },
  {
    id: 'd-major',
    name: 'D Major (2 Sharps: F#, C#)',
    root: 'D',
    type: 'major',
    description: 'Triumphant key: D, E, F#, G, A, B, C#',
    notes: ['D', 'E', 'F#', 'G', 'A', 'B', 'C#'],
  },
  {
    id: 'f-major',
    name: 'F Major (1 Flat: Bb/A#)',
    root: 'F',
    type: 'major',
    description: 'Pastoral warm key: F, G, A, A#, C, D, E',
    notes: ['F', 'G', 'A', 'A#', 'C', 'D', 'E'],
  },
  {
    id: 'a-minor',
    name: 'A Natural Minor',
    root: 'A',
    type: 'minor',
    description: 'Relative minor of C Major with all natural white keys: A, B, C, D, E, F, G',
    notes: ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
  },
  {
    id: 'e-minor',
    name: 'E Natural Minor (1 Sharp)',
    root: 'E',
    type: 'minor',
    description: 'Melancholic guitar/piano favorite: E, F#, G, A, B, C, D',
    notes: ['E', 'F#', 'G', 'A', 'B', 'C', 'D'],
  },
  {
    id: 'pentatonic-major',
    name: 'C Major Pentatonic',
    root: 'C',
    type: 'pentatonic',
    description: 'Pure 5-note melodic scale: C, D, E, G, A (no dissonant semitones)',
    notes: ['C', 'D', 'E', 'G', 'A'],
  },
  {
    id: 'blues-c',
    name: 'C Blues Scale',
    root: 'C',
    type: 'blues',
    description: 'Expressive 6-note blues scale with blue note: C, D#, F, F#, G, A#',
    notes: ['C', 'D#', 'F', 'F#', 'G', 'A#'],
  },
];


